name: AnalyticsPy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - ipython
  - jupyter
  - jupyterlab
  - numpy
  - numba
  - pyarrow
  - pytorch
  - scikit-learn
  - gensim
  - scipy
  - nltk
  - flask
  - bs4
  - tabulate
  - tqdm
  - pyyaml
  - pip:
    - pep8
    - autopep8
    - torchtext
  