name: PyBox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - ipython
  - jupyter
  - numpy
  - numba
  - pyarrow
  - pytorch
  - plotly
  - scikit-learn
  - gensim
  - scipy
  - nltk
  - flask
  - selenium
  - bs4
  - tqdm
  - pyyaml
  - lxml
  - spacy
  - spacy-lookups-data
  - whichcraft
  - pip:
    - pep8
    - autopep8
    - torchtext
    - xmltodict
    - msedge-selenium-tools
    - pybind11
    - cppimport
    - arch
    - numdifftools
    - tabulate
  